### ISSUE TITLE
Sync 'complete' but network activity and updates occurring in background

### ISSUE THREAD

**Issue by mcackay** [phantomfish/byline#1]
ISSUE:
The sync indicator only seems to show during the first part of the sync operation (perhaps the bit where you're talking to Feedly). It then disappears, suggesting you're all synced -- but there's still updates occurring in the background -- as shown by the IOS 'network activity' spinner.

Also, when reading a message you can sometimes see the system network spinner, but you don't know if it's Byline or something else.

Suggestions:
1) When in the message list views, ensure the Byline sync progress indicator displays whenever there is sync/cache/etc activity occurring. Perhaps change the text from "Syncing" to "Caching" if there are two (or more) steps, etc.
2) When viewing a message: Add a thin (2-3px) progress bar which creeps along below the top title bar (or above bottom nav bar) to show something is happening (or stripped band if % unknown).

**Comment by phantomfish** [comment]
The "syncing" message only displays while byline is actually fetching new items — this is by design.

Caching status is indicated in the settings, and while connected through the network activity spinner in the status bar (which by the way always only refers to the foreground app). I will consider a more prominent display that caching is in progress, but as this can be a long process and downloads are initiated somewhat at the discretion of the system (this is how background downloads work) it might be overkill.

The only other kind of spontaneous network activity is when Byline sends read/saved states back to Feedly, without doing a full sync. But this is generally triggered when you close the app, so there's not much point in a special status indicator for this.

I don't think it's necessary to indicate syncing/caching status when viewing articles.
